### ISSUE TITLE
different nail sizes

### ISSUE THREAD

**Issue by vonglahn** [eouia/MMM-OClock#1]
Hi there,

today I want to use your great module. I want to setup a clock (Hour, Minute and Second) but I only want Nails for Hours and Minutes not for the seconds. As far as I understand this can't be setup with you module.

Maybe something like this would be nice to have?
nailSize: [30,30,0],

Best Regards

Chris

**Comment by eouia** [comment]
Sorry, Without source modification it couldn't be at this moment. I'll consider it on next update.

**Comment by eouia** [comment]
I'm considering your issue, but making each hand configurable seems somewhat over-spec. I think that kind of feature is rarely used by other people.
Anyway, I have no plan to update as soon. So you can modify source by yourself to solve this issue.

Open `MMM-OClock.js` And look inside around line 275. 

https://github.com/eouia/MMM-OClock/blob/84632d64aaf4397b31eec69acbedb143f7d32c5d/MMM-OClock.js#L275-L276

```js
...
  drawPost: function(ctx, item) {
      if (item.h == "second") return // < - Add this line.
      if (this.config.useNail) {
...
```
